# Generated by Django 3.2 on 2023-09-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#0000FF', 'Синий'), ('#FF6600', 'Жёлтый'), ('#008000', 'Зелёный')], max_length=7, unique=True),
        ),
    ]
